# Generated by Django 4.1.3 on 2022-12-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles'),
        ),
    ]
